In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
healthy_features_path = 'featuresvalues.csv'
tumor_features_path = 'tumorfeatures.csv'

In [3]:
data = pd.read_csv(healthy_features_path)
data

1  2  3           4           5          6           7           8  \
0   0.312711  0  0   96.625630   85.937500  30.937500   90.336624   90.336624   
1   0.702091  0  0   79.821001   61.992188  65.585938   78.452682   78.452682   
2   0.691442  0  0   67.548490   64.414062  51.796875   70.155304   70.155304   
3   0.207779  0  0  156.088068   78.164062  35.937500  132.375551  132.375551   
4   0.282777  0  0  100.612953   52.338000  41.184000   95.669886   95.669886   
..       ... .. ..         ...         ...        ...         ...         ...   
75  0.193854  0  0  162.396489   70.312500  26.367188  141.827003  141.827003   
76  0.335641  0  0  100.225046   54.687500  48.828125   88.307389   88.307389   
77  0.532818  0  0   54.400939   34.179688  41.015625   51.563980   51.563980   
78  0.184894  0  0  172.443819  122.812500  29.062500  133.721156  133.721156   
79  0.444129  0  0  103.257478   91.298750  50.031150  111.974944  108.974944   

            4.1  Unnamed: 9  ...  Unnamed: 98  Unnamed: 99  Unnamed: 100  \
0   1429.723612   30.215894  ...     0.021158     4.950082      0.140360   
1   2318.384043   56.041604  ...     0.014458     5.678697      0.136410   
2   2198.023097   46.705885  ...     0.020683     7.113756      0.159100   
3   1908.062490   32.431834  ...     0.027838     5.966807      0.337106   
4   1488.830343   28.451027  ...     0.025614     5.595331      0.160192   
..          ...         ...  ...          ...          ...           ...   
75  2212.206523   31.481219  ...     0.027410     5.661709      0.243142   
76  1618.226369   33.639606  ...     0.012035     6.291807      0.299544   
77   652.949015   28.985823  ...     0.024009     5.611265      0.248266   
78  1576.831055   31.883750  ...     0.030018     5.640576      0.406452   
79  3150.920105   57.830814  ...     0.003056     7.292279      0.277393   

    Unnamed: 101  Unnamed: 102  Unnamed: 103  Unnamed: 104  Unnamed: 105  \
0    1755.084130      2.492708      0.004271     23.053272      0.013157   
1     559.907954      2.690750      0.003352     34.023626      0.019771   
2    1641.650580      0.073083      0.004445   1006.778331      0.121947   
3      22.895755      1.662553      0.006002     83.262073      0.079386   
4     811.998073      1.168050      0.005002     42.698793      0.015685   
..           ...           ...           ...           ...           ...   
75    131.112058      2.948380      0.003997     73.166907      0.056923   
76     35.919704      0.329676      0.007996    423.064167      0.035987   
77     48.664024      0.268894      0.027179     92.863090      0.062765   
78      9.481230      1.729093      0.004740    185.259795      0.068346   
79     82.017864      0.071760      0.004713   1174.227189      0.083357   

    Unnamed: 106  Unnamed: 107  
0       0.220057             0  
1       0.225209             0  
2      20.989892             0  
3       0.502555             0  
4       0.535532             0  
..           ...           ...  
75      0.501311             0  
76      4.055273             0  
77      3.732317             0  
78      0.938922             0  
79     15.020258             0  

[80 rows x 108 columns]

In [4]:
X_healthy = data.iloc[:, :-1]

In [5]:
X_healthy.values.shape

(80, 107)

In [6]:
X_healthy.values.dtype

dtype('float64')

In [7]:
y_healthy = data.iloc[:, -1]

In [8]:
y_healthy.values.shape

(80,)

In [9]:
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6]])

# New row to add
new_row = np.array([7, 8, 9])

# Adding a new row using np.vstack()
modified_array = np.vstack((existing_array, new_row))
print(modified_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
data_tumor = pd.read_csv(tumor_features_path)
data_tumor

1  2  3           4           5           6           7  \
0    0.319353  0  0  125.477002   44.687500  117.734375  135.064117   
1    0.268981  0  0  171.110519   51.562500  126.328125  189.462468   
2    0.316529  0  0  124.029475   42.109375   71.328125  115.872307   
3    0.372188  0  0  168.512073   52.421875  124.609375  153.086989   
4    0.393667  0  0  134.186998   48.125000  128.046875  141.942633   
..        ... .. ..         ...         ...         ...         ...   
276  0.238967  0  0  267.300895  110.000000  148.671875  171.713792   
277  0.723967  0  0   53.692039   42.109375   55.000000   55.428022   
278  0.311220  0  0  170.212424   48.984375  108.281250  182.806657   
279  0.273835  0  0  128.562779   34.375000   71.328125  121.549169   
280  0.257815  0  0  161.593961   35.234375   92.812500  141.233255   

              8            9         10  ...  Unnamed: 98  Unnamed: 99  \
0    135.064117  2673.338826  40.071452  ...     0.015076     5.958638   
1    189.462468  3624.559530  46.025407  ...     0.001082     5.979361   
2    115.872307  2473.136902  39.258905  ...     0.015853     6.106666   
3    153.086989  3805.990601  62.718251  ...     0.005313     6.274624   
4    141.942633  2849.723307  52.824930  ...     0.010695     5.609935   
..          ...          ...        ...  ...          ...          ...   
276  171.713792  1465.234375  63.876119  ...     0.031078     5.278934   
277   55.428022   884.384155  38.871242  ...     0.025740     5.475583   
278  182.806657  2727.128092  52.973452  ...     0.025742     5.224807   
279  121.549169  1934.013367  35.204960  ...     0.005154     6.180942   
280  141.233255  2173.110962  41.661292  ...     0.032693     5.681340   

     Unnamed: 100  Unnamed: 101  Unnamed: 102  Unnamed: 103  Unnamed: 104  \
0        0.112009   2523.268838      2.473413      0.003323     29.072921   
1        0.300394     63.402622      0.312355      0.002028    456.073789   
2        0.306395     35.450356      1.605275      0.004038     93.577571   
3        0.269012     71.571276      0.767073      0.002570    351.204857   
4        0.432405      7.162694      2.307508      0.002424    135.190550   
..            ...           ...           ...           ...           ...   
276      0.121083   2009.603599      1.863040      0.004049     33.004101   
277      0.180159    136.511751      1.660235      0.007308     25.795424   
278      0.119204   3490.677242      4.764778      0.002315     21.245111   
279      0.143015    850.538600      0.155308      0.004182    368.726573   
280      0.271682    132.751783      2.036386      0.003247     75.952881   

     Unnamed: 105  Unnamed: 106  Unnamed: 107  
0        0.014504      0.227486             1  
1        0.023048      3.711866             1  
2        0.059002      0.409372             1  
3        0.012382      1.786180             1  
4        0.061111      0.243941             1  
..            ...           ...           ...  
276      0.011812      0.485635             1  
277      0.028896      0.328948             1  
278      0.012816      0.121341             1  
279      0.013234     10.172534             1  
280      0.043651      0.305322             1  

[281 rows x 108 columns]

In [11]:
X_tumor = data_tumor.iloc[:, :-1]
y_tumor = data_tumor.iloc[:, -1]

In [12]:
z=y_tumor.values.reshape(281,1)
z.shape

(281, 1)

In [13]:
h = y_healthy.values.reshape(80,1)


In [14]:
modified_array = np.vstack((z, h))
y = modified_array.reshape(1,361)
print(y)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0]]


In [15]:
z1=X_tumor.values.reshape(281,107)
h1 = X_healthy.values.reshape(80,107)
modified_array = np.vstack((z1, h1))
X = modified_array.reshape(107,361)
print(X)

[[ 3.19352960e-01  0.00000000e+00  0.00000000e+00 ...  8.03799466e-01
   1.15677630e+00  1.94830767e+00]
 [ 1.40132850e+00  5.87909771e-01  5.48909034e-01 ...  2.43103113e-02
   4.32686259e+00  1.43741988e+03]
 [ 4.88279424e-01  6.36809950e-01  1.10297777e+00 ...  1.61092895e-01
   5.96007379e+03  2.13052085e+00]
 ...
 [ 3.71331023e+02  3.21777316e-01  5.89020182e-01 ... -1.56000000e+02
   3.12000000e+02  2.41249031e+01]
 [ 7.42834603e+01 -1.05425063e+00  1.09174798e+07 ...  1.26571925e+03
   1.77893289e-01  1.62035640e-02]
 [ 2.61464344e-01  3.95397679e+01  4.92180800e-03 ...  1.17422719e+03
   8.33567720e-02  1.50202582e+01]]


In [16]:
print(X.shape)
X =X.reshape(361,107)
print(y.shape)
y = y.reshape(361,)

(107, 361)
(1, 361)


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
X

array([[3.19352960e-01, 0.00000000e+00, 0.00000000e+00, ...,
        2.90729208e+01, 1.45040192e-02, 2.27485932e-01],
       [2.68980583e-01, 0.00000000e+00, 0.00000000e+00, ...,
        4.56073789e+02, 2.30479400e-02, 3.71186617e+00],
       [3.16528833e-01, 0.00000000e+00, 0.00000000e+00, ...,
        9.35775712e+01, 5.90019360e-02, 4.09371981e-01],
       ...,
       [5.32818440e-01, 0.00000000e+00, 0.00000000e+00, ...,
        9.28630904e+01, 6.27653120e-02, 3.73231658e+00],
       [1.84893549e-01, 0.00000000e+00, 0.00000000e+00, ...,
        1.85259795e+02, 6.83462340e-02, 9.38922215e-01],
       [4.44129378e-01, 0.00000000e+00, 0.00000000e+00, ...,
        1.17422719e+03, 8.33567720e-02, 1.50202582e+01]])

In [19]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [20]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, f1_score


In [23]:
y_pred_probs = rf_classifier.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)
# print(len(y_pred))
# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_probs)
f1 = f1_score(y_test, y_pred)

# Calculate sensitivity (recall) and specificity
tp, fn, fp, tn = confusion_mat.ravel()
sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

metrics_dict = {
    'Accuracy': accuracy,
    'Sensitivity (Recall)': sensitivity,
    'Specificity': specificity,
    'Confusion Matrix': confusion_mat,
    'Classification Report': classification_rep,
    'ROC AUC': roc_auc,
    'F1 Score': f1
}

In [24]:
metrics_dict

{'Accuracy': 0.9726027397260274,
 'Sensitivity (Recall)': 0.875,
 'Specificity': 1.0,
 'Confusion Matrix': array([[14,  2],
        [ 0, 57]]),
 'Classification Report': '              precision    recall  f1-score   support\n\n           0       1.00      0.88      0.93        16\n           1       0.97      1.00      0.98        57\n\n    accuracy                           0.97        73\n   macro avg       0.98      0.94      0.96        73\nweighted avg       0.97      0.97      0.97        73\n',
 'ROC AUC': 0.9375,
 'F1 Score': 0.9827586206896551}

In [25]:
#XGboost
from xgboost import XGBClassifier

xgb_classifier = XGBClassifier(n_estimators=100, learning_rate=0.02, random_state=42)
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.02, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [26]:
y_pred_probs = xgb_classifier.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_probs)
f1 = f1_score(y_test, y_pred)

# Calculate sensitivity (recall) and specificity
tp, fn, fp, tn = confusion_mat.ravel()
sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

metrics_dict = {
    'Accuracy': accuracy,
    'Sensitivity (Recall)': sensitivity,
    'Specificity': specificity,
    'Confusion Matrix': confusion_mat,
    'Classification Report': classification_rep,
    'ROC AUC': roc_auc,
    'F1 Score': f1
}

In [27]:
metrics_dict

{'Accuracy': 1.0,
 'Sensitivity (Recall)': 1.0,
 'Specificity': 1.0,
 'Confusion Matrix': array([[16,  0],
        [ 0, 57]]),
 'Classification Report': '              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        16\n           1       1.00      1.00      1.00        57\n\n    accuracy                           1.00        73\n   macro avg       1.00      1.00      1.00        73\nweighted avg       1.00      1.00      1.00        73\n',
 'ROC AUC': 1.0,
 'F1 Score': 1.0}

In [28]:
from sklearn.svm import SVC

In [29]:
svm_classifier = SVC(C=1, kernel= 'linear', random_state=42)
svm_classifier.fit(X_train, y_train)

In [ ]:
y_pred_probs = svm_classifier.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_probs)
f1 = f1_score(y_test, y_pred)

# Calculate sensitivity (recall) and specificity
tp, fn, fp, tn = confusion_mat.ravel()
sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

metrics_dict = {
    'Accuracy': accuracy,
    'Sensitivity (Recall)': sensitivity,
    'Specificity': specificity,
    'Confusion Matrix': confusion_mat,
    'Classification Report': classification_rep,
    'ROC AUC': roc_auc,
    'F1 Score': f1
}

In [ ]:
metrics_dict